package com.chrisren.learnmybatis3.mbg.entity;

import java.util.Date;

public class TCarInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_info.id
     *
     * @mbg.generated Sat Apr 23 17:29:03 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_info.car_no
     *
     * @mbg.generated Sat Apr 23 17:29:03 CST 2022
     */
    private String carNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_info.car_name
     *
     * @mbg.generated Sat Apr 23 17:29:03 CST 2022
     */
    private String carName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_info.created_by
     *
     * @mbg.generated Sat Apr 23 17:29:03 CST 2022
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_info.created_date
     *
     * @mbg.generated Sat Apr 23 17:29:03 CST 2022
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_info.updated_by
     *
     * @mbg.generated Sat Apr 23 17:29:03 CST 2022
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_info.updated_date
     *
     * @mbg.generated Sat Apr 23 17:29:03 CST 2022
     */
    private Date updatedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_info.id
     *
     * @return the value of t_car_info.id
     *
     * @mbg.generated Sat Apr 23 17:29:03 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_info.id
     *
     * @param id the value for t_car_info.id
     *
     * @mbg.generated Sat Apr 23 17:29:03 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_info.car_no
     *
     * @return the value of t_car_info.car_no
     *
     * @mbg.generated Sat Apr 23 17:29:03 CST 2022
     */
    public String getCarNo() {
        return carNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_info.car_no
     *
     * @param carNo the value for t_car_info.car_no
     *
     * @mbg.generated Sat Apr 23 17:29:03 CST 2022
     */
    public void setCarNo(String carNo) {
        this.carNo = carNo == null ? null : carNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_info.car_name
     *
     * @return the value of t_car_info.car_name
     *
     * @mbg.generated Sat Apr 23 17:29:03 CST 2022
     */
    public String getCarName() {
        return carName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_info.car_name
     *
     * @param carName the value for t_car_info.car_name
     *
     * @mbg.generated Sat Apr 23 17:29:03 CST 2022
     */
    public void setCarName(String carName) {
        this.carName = carName == null ? null : carName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_info.created_by
     *
     * @return the value of t_car_info.created_by
     *
     * @mbg.generated Sat Apr 23 17:29:03 CST 2022
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_info.created_by
     *
     * @param createdBy the value for t_car_info.created_by
     *
     * @mbg.generated Sat Apr 23 17:29:03 CST 2022
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_info.created_date
     *
     * @return the value of t_car_info.created_date
     *
     * @mbg.generated Sat Apr 23 17:29:03 CST 2022
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_info.created_date
     *
     * @param createdDate the value for t_car_info.created_date
     *
     * @mbg.generated Sat Apr 23 17:29:03 CST 2022
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_info.updated_by
     *
     * @return the value of t_car_info.updated_by
     *
     * @mbg.generated Sat Apr 23 17:29:03 CST 2022
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_info.updated_by
     *
     * @param updatedBy the value for t_car_info.updated_by
     *
     * @mbg.generated Sat Apr 23 17:29:03 CST 2022
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_info.updated_date
     *
     * @return the value of t_car_info.updated_date
     *
     * @mbg.generated Sat Apr 23 17:29:03 CST 2022
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_info.updated_date
     *
     * @param updatedDate the value for t_car_info.updated_date
     *
     * @mbg.generated Sat Apr 23 17:29:03 CST 2022
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_info
     *
     * @mbg.generated Sat Apr 23 17:29:03 CST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TCarInfo other = (TCarInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCarNo() == null ? other.getCarNo() == null : this.getCarNo().equals(other.getCarNo()))
            && (this.getCarName() == null ? other.getCarName() == null : this.getCarName().equals(other.getCarName()))
            && (this.getCreatedBy() == null ? other.getCreatedBy() == null : this.getCreatedBy().equals(other.getCreatedBy()))
            && (this.getCreatedDate() == null ? other.getCreatedDate() == null : this.getCreatedDate().equals(other.getCreatedDate()))
            && (this.getUpdatedBy() == null ? other.getUpdatedBy() == null : this.getUpdatedBy().equals(other.getUpdatedBy()))
            && (this.getUpdatedDate() == null ? other.getUpdatedDate() == null : this.getUpdatedDate().equals(other.getUpdatedDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_info
     *
     * @mbg.generated Sat Apr 23 17:29:03 CST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCarNo() == null) ? 0 : getCarNo().hashCode());
        result = prime * result + ((getCarName() == null) ? 0 : getCarName().hashCode());
        result = prime * result + ((getCreatedBy() == null) ? 0 : getCreatedBy().hashCode());
        result = prime * result + ((getCreatedDate() == null) ? 0 : getCreatedDate().hashCode());
        result = prime * result + ((getUpdatedBy() == null) ? 0 : getUpdatedBy().hashCode());
        result = prime * result + ((getUpdatedDate() == null) ? 0 : getUpdatedDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_info
     *
     * @mbg.generated Sat Apr 23 17:29:03 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", carNo=").append(carNo);
        sb.append(", carName=").append(carName);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", updatedDate=").append(updatedDate);
        sb.append("]");
        return sb.toString();
    }
}